sonar.projectKey=LeisuredRainbow_travel-agency-frontend
sonar.organization=leisuredrainbow
sonar.projectName=travel-agency-frontend
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://sonarcloud.io