sonar.projectKey=LeisuredRainbow_travel-agency-frontend
sonar.organization=leisuredrainbow
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
sonar.host.url=https://sonarcloud.io